### ISSUE TITLE
Generated RPM has a -1 in the filename for some reason

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-rpm#3]
Command:
> go-bin-rpm generate -f rpm-creation-data.json --version 0.0.1 -a x86_64

Expected filename: 
> go-github-release-test-0.0.1.x86_64.rpm

Actual filename:
> go-github-release-test-0.0.1-1.x86_64.rpm

**Comment by mh-cbon** [comment]
rpm has a naming conviention

http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html

name-version-release.architecture.rpm

**Comment by solvingj** [comment]
I agree it's a debatable matter of opinion, but it's important to point out that it's only a convention, not a requirement, and doesn't make sense in many cases.  I submit that it should not be enforced since the user can specify it if they wish.  It should be left to the packager.  Indeed, your own rpm packages don't even follow the convention, and neither do many other modern projects. 

I.E.
https://github.com/mh-cbon/go-bin-rpm/releases
https://github.com/mh-cbon/changelog/releases
