### ISSUE TITLE
Base Fedora Docker Image does not have rpmbuild

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-rpm#5]
I was trying to understand the contents of create-package.sh and I found this:

```
docker run -v $PWD/:${TRAVIS_BUILD_DIR} fedora /bin/sh -c "cd ${TRAVIS_BUILD_DIR} && sh ./docker.sh"
sudo chown travis:travis ./*-*.rpm

```

This fedora docker image returns the following error when trying to use go-bin-rpm in it: 

`exec: "rpmbuild": executable file not found in $PATH`

Obviously mh-cbon was able to package RPM's on this image, but I don't understand how. 

Can anyone comment?

**Comment by mh-cbon** [comment]
sudo yum install rpm-build -y

https://github.com/mh-cbon/go-bin-rpm/blob/master/go-bin-rpm-utils/create-pkg.go#L26

https://github.com/mh-cbon/go-bin-rpm/blob/master/create-pkg.sh#L77
