### ISSUE TITLE
"generate --output" requires a filename, docs indicate it should take directory (and it should)

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-bin-rpm#6]
The documentation says the following:

>  -o value, --output value      Output package to this path

The documentation for go-bin-deb says the following:

> -output value, -o value  Output directory for the debian package files

In the case of this library (go-bin-rpm), i have to provide a file path with the full filename. 

It would be vastly preferred if it actually did take a "directory" because the tool generates the correct filenames inside the pkg-build directory, and I just want to copy the result file out to a destination directory.

**Comment by solvingj** [comment]
Here's what happens when I use option:   "-o ."

```
Wrote: /mnt/travis/pkg-build/RPMS/x86_64/go-github-release-test-251.1.0-1.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.hhQp2I
+ umask 022
+ cd /mnt/travis/pkg-build/BUILD
+ exit 0
open /mnt/travis/pkg-build/RPMS/x86_64/go-github-release-test-251.1-1.x86_64.rpm: no such file or directory
```

**Comment by mh-cbon** [comment]
> It would be vastly preferred if it actually did take a "directory" because the tool generates the correct filenames inside the pkg-build directory, and I just want to copy the result file out to a destination directory.

what s the difference with --output flag which will put the file in place directly ?

**Comment by solvingj** [comment]
I don't remember exactly how this worked, but can you confirm if the command requires a file path or a directory path?

**Comment by mh-cbon** [comment]
done https://github.com/mh-cbon/go-bin-rpm/commit/f6b24e43d09d66cc51ab68e8bcca2cf89f1cff64#diff-04c6e90faac2675aa89e2176d2eec7d8R148
